### ISSUE TITLE
migrating the 'git-branch-status' script gist to github

### ISSUE THREAD

**Issue by bill-auger** [bill-auger/git-branch-status#1]
i @ mention all of the nicks below who have either forked, contributed, starred, or commented on the ['git-branch-status'](https://gist.github.com/bill-auger/9335fe2633eae38d3070) script gist - it is unfortunately the case that github does not notify anyone of comments to gists so they can only be seen by browsing to the gist web page explicitly - i have been planning for some time to move this script to github and give it a GPL so that it can have an issue tracker and be properly shared - the original author and contributors have agreed this was a good idea but i have not yet gotten around to it - i thought of this again today and noticed that a bug was reported over a month ago so i suppose the migration should not be delayed any longer

it would be sweet if everyone mentioned here would star or even watch this repo and/or otherwise help improve the script by reporting bugs, suggesting feature requests, or by contributing any changes you may have made - and who knows perhaps someday git may want to incorporate it officially

over the years the script has gotten quite a bit of attention as you can see from the number of nicks below but the logistics of maintaining and collaborating on anything useful as a gist are just ridiculous - it is also unclear how anyone is finding it (if they are landing on jehiah's base fork or mine or what) - jehiah's original version from 2011 has 40 stars on it now so it is clear that many finding it are not aware of any updates - for this reason it would probably be best to replace the content of the gist with a link to this repo and ideally the current forks would all pull that in so that it can be more clear who has contributed updates and where the most current HEAD is located

i will tend to the bug reported by mikea soon and transfer the repo here - for now i just wanted to bring everyone in on the same page - even this was quite a chore collecting nicks throughout the fork graph

my version which seems to be the most advanced has the lineage [ @jehiah -> @kd35a -> @knovoselic ] and although we have discussed this by email it would be nice if you three would comment on this thread giving your explicit approval of adding a GPL3 to the script

**Comment by bill-auger** [comment]
@jehiah @kd35a @knovoselic @Eldelshell @kierun @ava-dylang @mikea @pabranch @kirkportas @willemp @duub @sroze @hmcfletch @BullyEntertainment @kindlychung @jharrys @alejandrodumas @lth2h @zeroeth @knowncitizen @Rud5G @Icehunter @ncolton @kevinawoo @rgallo @fredrikhl @amadu80 @mclarkson @RomuloOliveira @philgreenyouilabs @SGSJohnny @Mark-Booth @ElderMael @Elisabeth-Engel @jakar @hellodarren @capnslipp @yuki-kimoto @rgenoud @tinacious @bendangelo @BraveNewMath @mirobeka @minmax

please note the post above :)

**Comment by bill-auger** [comment]
@kyounger @WIZARDISHUNGRY @biannetta @exalted @steadystatic @patrickread @bacondropped @abrabah @assaff @freen @jasonseney @SaphirePhenux @fjuniorr @johndrinkwater @benrowe @NigelGreenway @abal5 @javabrett @piotros @jaypuk @dlenski @vishwas-g @glnster @montylounge @linniksa @tomquas @tizgrape @kaptoxic @gg7 @sashaegorov @urecio @dwettlaufer @JoseCage @BimbaLaszlo @porcupo @redders6600 @idomitori @allex @KrullKorg @picur

please note the post above

**Comment by bill-auger** [comment]
my version which seems to be the most advanced has the lineage [ @jehiah -> @kd35a -> @knovoselic ] and although we have discussed this by email it would be nice if you three would comment on this thread giving your explicit approval of adding a GPL3 to the script

**Comment by javabrett** [comment]
I just want to make sure that you are aware of [jwiegley/git-scripts](https://github.com/jwiegley/git-scripts) (673 stars, 111 forks, 175 commits, 19 contributors), which has been for me the gold-standard collection of randomly-collected-and-maintained git-scripts, which I generally clone and alias into my development-environments.  The main drawcard of this one for me was it had the best copy as far as I could tell of [git-svn-diff](https://github.com/jwiegley/git-scripts/blob/master/git-svn-diff), an important script for `git-svn` fans.

So, if you get the licensing clarified, that is another option for a home for this which might inherit a number of followers.  Not to suggest that adding it there clarifies the license at all.  Nor does it give you insurance that you'll be able to maintain the scripts there, but my experience has been that solid PRs get promptly merged.  You could maybe engage @jwiegley to see if they are interested in making an org project of it.

**Comment by kd35a** [comment]
@bill-auger I generally tend to prefer a more liberal licensing like MIT or BSD, but I'm fine with GPLv3 also! :) Good initiative!

**Comment by kierun** [comment]
Many thanks indeed.

**Comment by jwiegley** [comment]
I also prefer MIT or BSD.

**Comment by jehiah** [comment]
@bill-auger :thumbsup: I have no preference of license.

**Comment by thorsummoner** [comment]
I would prefer GPL
MIT (expat) and BSD (3 or 4 clause) licenses don't protect derivative work and dependent work like the gpl does.

**Comment by bill-auger** [comment]
to elaborate on what thorsummoner said - for me it is not about protecting the work but the reason i prefer the GPL is that it aims to foster collaboration and help the project move forward by requiring anyone who improves the program to share the improvement - in this way improving the program not just for themselves but for everyone

i could see how that would not be important for simple scripts like many of those in jwiegley's collection which are actually better suited as alias commands - perhaps they are already as concise and 'finished' as they could be and so may not even possible to improve upon but the more complex a program gets then there is always room for improvement - the fact that i am getting bug reports for example is a clear sign that this script is complex enough to require stewardship which is the very reason i wanted to move it to github - if i just wanted to "set it loose" and forget about maintaining it i could have just left it as it was in a gist without a license because being a gist implies to most people that this is just a "snippet" that is so trivial as not to be worthy of a license at all

**Comment by bill-auger** [comment]
btw @jwiegley - that is indeed an impressive collection and thanks to @javabrett for showing me this - i can definitely see the advantage of consolidating such a collection that ppl can simply clone into a fresh distro - i would not mind this script being included there but for the reasons mentioned above and because it already has it's own commit history i would prefer that it not be simply copied into the collection - i would suggest that @jwiegley could include this repo as a submodule which would allow his users to pull it in easily while still retaining it's identity and more importantly it's issue tracker

**Comment by jwiegley** [comment]
@bill-auger How about if I use `git-subtree`, to pull in a copy of your history, while retaining the ability to update/pull in the future?

**Comment by knowncitizen** [comment]
Overall no preference.  Thanks for including!

**Comment by bill-auger** [comment]
@jwiegley - being a submodule still allows updating - ive not used subtree merge before but i just read up on it - so it looks like subtree merge would be simpler for the end user - as a submodule each user would need to explicitly update the submodule but it seems that as a subtree the subtree merge needs only be done once on the repo and users could simply pull it in one shot along with the rest - yes?

**Comment by jwiegley** [comment]
Exactly.  From a repository-contents point of view, the two are entirely equivalent and you can freely convert between the two representations.  Subtrees requires a bit more work from the maintainer, but come with the benefit that no one has to deal with them as a consumer.

**Comment by bill-auger** [comment]
@jwiegley

ok great - all contributers have chimed in with their consent and i have the code uploaded in a good state now so feel free to do this yourself if you like - regarding updates it would be nice if github had a more useful commication system but i dont expect to update very often - would you be watching the repo for changes or should i fork your repo and send a PR whenever ?

**Comment by jwiegley** [comment]
A PR would be the most helpful.  In fact, as I am getting ready to head out on vacation, do you want to start the ball rolling with such a PR? :)

**Comment by bill-auger** [comment]
@jwiegley - ah you want me to learn a new git trick today - good doobie

no rush - id still like to see @knovoselic chime in here too - i will send a PR after i squash #2

**Comment by knovoselic** [comment]
Hi everyone. I'm glad this repo is finally alive! I'd prefer GPL licence and agree with everything else. Good job @bill-auger  :)
