### ISSUE TITLE
Comparing Remote branches

### ISSUE THREAD

**Issue by chippinkston** [bill-auger/git-branch-status#10]
On a project I'm working on, we had to maintain an upstream and downstream pair of repositories while changing hosting providers.  Now that we've finished the move, I'm trying to run down any code delta's that are on the old upstream repo.  Is there any way to use this to get the status of branches between two remotes?

**Comment by bill-auger** [comment]
yes, that use case is noted in the USAGE message

$ git-branch-status --help
....
  # compare two arbitrary branches (either local and either remote)
  $ git-branch-status remote-a/arbitrary-branch remote-b/arbitrary-branch
....

you only need to ensure that the remotes have been fetched first

**Comment by bill-auger** [comment]
yes, that use case is noted in the USAGE message

```
$ git-branch-status --help
....
  # compare two arbitrary branches (either local and either remote)
  $ git-branch-status remote-a/arbitrary-branch remote-b/arbitrary-branch
....
```

you only need to ensure that the remotes have been fetched first
