### ISSUE TITLE
Feature request: porcelain version

### ISSUE THREAD

**Issue by najamelan** [bill-auger/git-branch-status#3]
This tool is really nice for scripting, but parsing the report is a bit of a pain. It would be nice to be able to ask the situation for a branch and get a oneline output, maybe like:
`origin 1 -2`
Or even if the remote can be specified, just:
`1 -2`
Personally I'm looking for the simplest way to tell if a remote branch can be pulled --ff-only without actually doing the pull...

**Comment by bill-auger** [comment]
if that is all you wanted you could get that like this

```
remote="origin"
branch="master"
ahead=$(git rev-list $branch..$remote/$branch --count) 
behind=$(git rev-list $remote/$branch..$branch --count) 
echo "$remote/$branch $ahead $behind"
```

you could also use ```git --dry-run``` for your specific purpose

**Comment by najamelan** [comment]
Ok, 

thank you for the tips, I'll most likely do it like that then. Ill still keep git-branch-status for my own pleasure when using the command line ;)

**Comment by bill-auger** [comment]
yes that specifically what i use it for is the visual overview
