### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by atomkirk** [bill-auger/git-branch-status#4]
For posterity, maybe you could add to readme or make a wiki page that describes how to make this work on mac:

1. Install `brew install homebrew/dupes/grep` which places gnu grep in your path as `ggrep`
2. Replace uses of `grep` in script with `ggrep`

**Comment by bill-auger** [comment]
@atomkirk -

i dont have a mac myself but i asked some peeps on the IRC to help me trouble shoot this - real solutions are always better than caveats - could you instead try this version i just pushed as the 'mac' branch - i think it should work with the default BSD grep on mac without modification

https://github.com/bill-auger/git-branch-status/tree/mac

**Comment by atomkirk** [comment]
Yes that works great!

**Comment by bill-auger** [comment]
sweet - i will get this patch into the master branch soon
