### ISSUE TITLE
Column Width in Reports too small

### ISSUE THREAD

**Issue by nmccready** [bill-auger/git-branch-status#5]
How does one configure the column width?

**Comment by bill-auger** [comment]
look on line 116 https://github.com/bill-auger/git-branch-status/blob/master/git-branch-status#L116
```
MAX_COL_W=27
```

just change the 27 to something else

o/c if you have a branch name that is 100 chars long then even MAX_COL_W=99 will be "too small"

**Comment by nmccready** [comment]
Thanks
