### ISSUE TITLE
Dumb Question - How do I use this?

### ISSUE THREAD

**Issue by idkjs** [bill-auger/git-branch-status#7]
I tried adding the script to my dotfiles on macOS. Everytime i run `git-branch-status` the terminal window closes with something like `The terminal process terminated with exit code: 1`. Sorry for rookie question. Thank you for sharing and helping if you can.

**Comment by bill-auger** [comment]
this is probably because the BASH shell on a mac is slightly different than GNU BASH - it probably just needs a bit of tweaking to make it work on a mac - could you try the latest version on the development branch?

https://raw.githubusercontent.com/bill-auger/git-branch-status/development/git-branch-status

**Comment by idkjs** [comment]
Same result except now I dont get the error. The bash window opens and then closes immediately.

**Comment by bill-auger** [comment]
i have it working on libertybsd now - that may satisfy a mac also

https://raw.githubusercontent.com/bill-auger/git-branch-status/development/git-branch-status

**Comment by knovoselic** [comment]
@idkjs I'm on MacOS as well (10.13.3) and latest linked script works fine. Can you add more info about your setup? How exactly are you running the script? Did you try different repository?

**Comment by idkjs** [comment]
@knovoselic  thanks for feedback, boss. 

- [.bash_profile](https://github.com/idkjs/dotfiles/blob/c382dc060c8b0bc979eebb0df841424fe3bfa19a/.bash_profile#L19)
```
...
source "${HOME}/dotfiles/git-branch-status"
...
```

[dotifile/git-branch-status](https://github.com/idkjs/dotfiles/blob/c382dc060c8b0bc979eebb0df841424fe3bfa19a/git-branch-status#L1) is cp of link above.

Probably did something stupid. Happy for the feedback!

**Comment by knovoselic** [comment]
@idkjs what exactly are you trying to accomplish? It fails for me as well is I source it. But it was never meant to be sourced like that.
I'm a bit confused as why you'd want to source the script. Do you want to run it each time you open up a new terminal? Or are you trying to do something else?
If you just want to be able to call it like `git branch-status` from anywhere, you only need to put the script in some folder in your PATH and make sure it's executable. Also, it needs to be called git-branch-status (that's how when you call `git branch-status` git knows what to execute).

**Comment by bill-auger** [comment]
this script is not intended to be "sourced" - it is run just a standalone command in a terminal - just like what is shown in the README screenshot

```$ git-branch-status```

as knovoselic noted, you would put the script in your PATH or you could create an alias in your .bash_profile or .bash_aliases like:

```alias git-branch-status='/path/to/the/real/git-branch-status/git-branch-status'```

or in the [alias] section of your ~/.gitconfig

```
[alias]
branch-status = !/path/to/the/real/git-branch-status/git-branch-status
```

that would allow it to be used as a git sub "command"

```$ git branch-status```

one other thing i forgot - on BSD i had to change #!/bin/bash to #!/usr/bin/env bash - if bash is not in /bin on a mac then that could be something to note

**Comment by idkjs** [comment]
@bill-auger thank you so much for the detailed and didactic response. Learned a whole lot there. I will be studying your response. Again, thank you, sir.

**Comment by idkjs** [comment]
@knovoselic i had in my mind that this was an alternative command that I would run like my other git shortcuts, which you and @bill-auger have graciously explained is not the case. Thanks, sir.
